server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: payments-service
          uri: http://payments-service:8082
          predicates:
            - Path=/api/v1/payments/**

springdoc:
  swagger-ui:
    urls:
      - name: Payments Service
        url: /api/v1/payments/v3/api-docs
